[theme]
primaryColor="#ff4b4b"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f8f9fa"
textColor="#262730"
font="sans serif"

[server]
maxUploadSize = 500
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = false


